"""empty message

Revision ID: 06b9cca19ef8
Revises: 83c4bf549bf0
Create Date: 2024-06-07 14:22:59.223617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b9cca19ef8'
down_revision = '83c4bf549bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dance_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_img')

    with op.batch_alter_table('dance_classes', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
