"""empty message

Revision ID: 21407db0727d
Revises: df198d6818f8
Create Date: 2024-06-14 15:00:43.149797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21407db0727d'
down_revision = 'df198d6818f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_interviews_teacher_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    # ### end Alembic commands ###
