"""empty message

Revision ID: 586470f2fe4e
Revises: 7f96b2b94878
Create Date: 2024-06-09 22:18:07.307569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586470f2fe4e'
down_revision = '7f96b2b94878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
