"""empty message

Revision ID: 73f6fc70ba3a
Revises: 
Create Date: 2024-06-07 13:59:40.567108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f6fc70ba3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dance_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dance_style', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_dance_classes_teacher_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('dance_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dance_class_id'], ['dance_classes.id'], name=op.f('fk_enrollments_dance_class_id_dance_classes')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_enrollments_student_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_table('dance_classes')
    op.drop_table('users')
    # ### end Alembic commands ###
