"""empty message

Revision ID: 83c4bf549bf0
Revises: 73f6fc70ba3a
Create Date: 2024-06-07 14:12:11.172172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c4bf549bf0'
down_revision = '73f6fc70ba3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dance_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.drop_column('time')
        batch_op.drop_column('dance_style')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dance_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dance_style', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('style')

    # ### end Alembic commands ###
