"""empty message

Revision ID: df198d6818f8
Revises: 586470f2fe4e
Create Date: 2024-06-10 16:54:02.593585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df198d6818f8'
down_revision = '586470f2fe4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dance_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekday', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dance_classes', schema=None) as batch_op:
        batch_op.drop_column('weekday')

    # ### end Alembic commands ###
