"""empty message

Revision ID: fdb762535439
Revises: 06b9cca19ef8
Create Date: 2024-06-08 13:24:19.460911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb762535439'
down_revision = '06b9cca19ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dance_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dance_classes', schema=None) as batch_op:
        batch_op.drop_column('class_img')

    # ### end Alembic commands ###
